# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"  
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_URL: postgresql://postgres:password@postgres:5432/mydatabase  
#     volumes:
#       - .:/usr/src/app

#   postgres:
#     image: postgres:16.3
#     shm_size: 128mb
#     volumes:
#       - ./.docker/.volume/postgresql:/var/lib/postgresql
#       - ./.docker/postgresql/scripts/create-database.sql:/docker-entrypoint-initdb.d/init.sql
#     environment:
#       POSTGRES_PASSWORD: password
#     ports:
#       - 5432:5432

services:
   postgres:
    image: postgres:16.3
    shm_size: 128mb
    volumes:
      - ./.docker/.volume/postgresql:/var/lib/postgresql
      - ./.docker/postgresql/scripts/create-database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  
  